[versions]
fn = '1.0.131'
jakarta-inject = '2.0.1'
javapoet = '1.13.0'
jetty = '9.4.35.v20201120'
kotlin = '1.6.10'
micronaut-micrometer = '4.1.1'
micronaut-sql = '4.1.1'
mockito = '4.1.0'
slf4j-jcl = '1.7.36'

[libraries]
fn-api = { module = 'com.fnproject.fn:api', version.ref = 'fn' }
fn-runtime = { module = 'com.fnproject.fn:runtime', version.ref = 'fn' }
fn-testing-junit4 = { module = 'com.fnproject.fn:testing-junit4', version.ref = 'fn' }
jakarta-inject = { module = 'jakarta.inject:jakarta.inject-api', version.ref = 'jakarta-inject' }
javapoet = { module = 'com.squareup:javapoet', version.ref = 'javapoet' }
jetty = { module = 'org.eclipse.jetty:jetty-server', version.ref = 'jetty' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter-engine', version = '' }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
micronaut-groovy = { module = 'io.micronaut.groovy:micronaut-runtime-groovy', version = '' }
micronaut-micrometer = { module = 'io.micronaut.micrometer:micronaut-micrometer-core', version.ref = 'micronaut-micrometer' }
micronaut-sql-jdbc-hikari = { module = 'io.micronaut.sql:micronaut-jdbc-hikari', version.ref = 'micronaut-sql' }
micronaut-sql-jdbc-ucp = { module = 'io.micronaut.sql:micronaut-jdbc-ucp', version.ref = 'micronaut-sql' }
mockito = { module = 'org.mockito:mockito-core', version.ref = 'mockito' }
oci-common = { module = 'com.oracle.oci.sdk:oci-java-sdk-common', version = '' }
oci-database = { module = 'com.oracle.oci.sdk:oci-java-sdk-database', version = '' }
oci-monitoring = { module = 'com.oracle.oci.sdk:oci-java-sdk-monitoring', version = '' }
oci-objectstorage = { module = 'com.oracle.oci.sdk:oci-java-sdk-objectstorage', version = '' }
oci-secrets = { module = 'com.oracle.oci.sdk:oci-java-sdk-secrets', version = '' }
oci-vault = { module = 'com.oracle.oci.sdk:oci-java-sdk-vault', version = '' }
oci-loggingingestion = { module = 'com.oracle.oci.sdk:oci-java-sdk-loggingingestion', version = '' }
oracle-jdbc = { module = 'com.oracle.database.jdbc:ojdbc11', version = '' }
slf4j-jcl = { module = 'org.slf4j:jcl-over-slf4j', version.ref = 'slf4j-jcl' }

[plugins]
kotlin-allopen = { id = 'org.jetbrains.kotlin.plugin.allopen', version.ref = 'kotlin' }
kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
kotlin-kapt = { id = 'org.jetbrains.kotlin.kapt', version.ref = 'kotlin' }
